version: "3"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CLI_ARGS= #optional
    volumes:
      - /home/qdeli/self-hosted/duplicati/config:/config
      - /home/qdeli/self-hosted/duplicati/backups:/backups
      - /home/qdeli/self-hosted:/source
    ports:
      - 8200:8200
    restart: unless-stopped
  fb:
    image: filebrowser/filebrowser
    restart: unless-stopped
    container_name: filebrowser
    volumes:
      - /home/qdeli/self-hosted/media:/srv
    ports:
       - 8781:80