version: "3"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CLI_ARGS= #optional
    volumes:
      - /home/qdeli/self-hosted/duplicati/config:/config
      - /home/qdeli/self-hosted/duplicati/backups:/backups
      - /home/qdeli/self-hosted:/source
    ports:
      - 8200:8200
    restart: unless-stopped
  fb:
    image: filebrowser/filebrowser
    restart: unless-stopped
    container_name: filebrowser
    volumes:
      - /home/qdeli/self-hosted/media:/srv
    ports:
      - 8781:80
  dash:
    container_name: dash
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "8011:3001"
    environment:
      DASHDOT_PAGE_TITLE: "Raspberry Pi"
      DASHDOT_ENABLE_CPU_TEMPS: true
    volumes:
      - /:/mnt/host:ro
  kapowarr:
    container_name: kapowarr
    restart: unless-stopped
    volumes:
      - "/home/qdeli/self-hosted/media/db/kapowarr:/app/db"
      - "/home/qdeli/self-hosted/downloads/kapowarr:/app/temp_downloads"
      - "/home/qdeli/self-hosted/media/comics:/RF"
    ports:
      - "5656:5656"
    image: "mrcas/kapowarr:latest"
    platform: linux/arm64
  kavita:
    image: jvmilazz0/kavita:latest # Using the stable branch from the offical repo.
    container_name: kavita
    volumes:
      - /home/qdeli/self-hosted/media/manga:/manga # Manga is just an example you can have the name you want. See the following
      - /home/qdeli/self-hosted/media/comics:/comics # Use as many as you want
      - /home/qdeli/self-hosted/media/books:/books #
      - /home/qdeli/self-hosted/media/db:/kavita/config # Change './data if you want to have the config files in a different place.
        # /kavita/config must not be changed
    environment:
      - TZ=Your/Timezone
    ports:
      - "5000:5000" # Change the public port (the first 5000) if you have conflicts with other services
    restart: unless-stopped
  gotify:
    image: gotify/server-arm7
    container_name: gotify
    restart: unless-stopped
    ports:
      - 9898:80
    volumes:
      - "/home/qdeli/self-hosted/gotify/data:/app/data"