version: "3"
volumes:
  redisdata:
networks:
  db-network:
    external: true
  paperless:
    driver: bridge
    name: paperless
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CLI_ARGS= #optional
    volumes:
      - /home/qdeli/self-hosted/duplicati/config:/config
      - /home/qdeli/self-hosted/duplicati/backups:/backups
      - /home/qdeli/self-hosted:/source
    ports:
      - 8200:8200
    restart: unless-stopped
  fb:
    image: filebrowser/filebrowser
    restart: unless-stopped
    container_name: filebrowser
    volumes:
      - /home/qdeli/self-hosted/media:/srv
    ports:
      - 8781:80
  dash:
    container_name: dash
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "8011:3001"
    environment:
      DASHDOT_PAGE_TITLE: "Raspberry Pi"
      DASHDOT_ENABLE_CPU_TEMPS: true
    volumes:
      - /:/mnt/host:ro
  kapowarr:
    container_name: kapowarr
    restart: unless-stopped
    volumes:
      - "/home/qdeli/self-hosted/media/db/kapowarr:/app/db"
      - "/home/qdeli/self-hosted/downloads/kapowarr:/app/temp_downloads"
      - "/home/qdeli/self-hosted/media/comics:/RF"
    ports:
      - "5656:5656"
    image: "mrcas/kapowarr:latest"
    platform: linux/arm64
  kavita:
    image: jvmilazz0/kavita:latest # Using the stable branch from the offical repo.
    container_name: kavita
    volumes:
      - /home/qdeli/self-hosted/media/manga:/manga # Manga is just an example you can have the name you want. See the following
      - /home/qdeli/self-hosted/media/comics:/comics # Use as many as you want
      - /home/qdeli/self-hosted/media/books:/books #
      - /home/qdeli/self-hosted/media/db:/kavita/config # Change './data if you want to have the config files in a different place.
        # /kavita/config must not be changed
    environment:
      - TZ=Your/Timezone
    ports:
      - "5000:5000" # Change the public port (the first 5000) if you have conflicts with other services
    restart: unless-stopped
  gotify:
    image: gotify/server-arm7
    container_name: gotify
    restart: unless-stopped
    ports:
      - 9898:80
    volumes:
      - "/home/qdeli/self-hosted/gotify/data:/app/data"
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    devices:
        - "/dev/vchiq:/dev/vchiq"
        - "/dev/vcio:/dev/vcio"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
      - /home/qdeli/self-hosted/media/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd        
      - /usr/lib/aarch64-linux-gnu/libvcos.so.0:/usr/lib/aarch64-linux-gnu/libvcos.so.0        
      - /usr/lib/aarch64-linux-gnu/libvchiq_arm.so.0:/usr/lib/aarch64-linux-gnu/libvchiq_arm.so.0             
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    volumes:
      - /home/qdeli/self-hosted/media/influxdb/data:/var/lib/influxdb
    ports:
      - "8086:8086"

  chronograf:
    image: chronograf
    container_name: chronograf
    restart: always
    environment:
      INFLUXDB_URL: http://influxdb:8086
    volumes:
      - /home/qdeli/self-hosted/media/chronograf/data:/var/lib/chronograf
    ports:
      - "8888:8888"
    links:
      - influxdb
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://pwd.qdeli.ovh"  # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      SIGNUPS_ALLOWED: "false" # Deactivate this with "false" after you have created your account so that no strangers can register
    volumes:
      - /home/qdeli/self-hosted/vaultwarden:/data # the path before the : can be changed
    ports:
      - 11001:80 # you can replace the 11001 with your preferred port
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    networks:
      - paperless
      - db-network
    ports:
      - "8010:8000"
    volumes:
      - /home/qdeli/self-hosted/paperless/data:/usr/src/paperless/data
      - /home/qdeli/self-hosted/paperless/media:/usr/src/paperless/media
      - /home/qdeli/self-hosted/paperless/export:/usr/src/paperless/export
      - /home/qdeli/self-hosted/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: postgres-db
      PAPERLESS_DBUSER: qdeli
      PAPERLESS_DBPASS: 1997
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_OCR_LANGUAGE: fra
      DEBUG: true
      PAPERLESS_URL: "https://paperless.qdeli.ovh"
      PAPERLESS_OCR_PAGES: 1
      PAPERLESS_WEBSERVER_WORKERS: 1
      PAPERLESS_ENABLE_NLTK: false
      PAPERLESS_OCR_SKIP_ARCHIVE_FILE: with_text
  adguard:
    container_name: adguard
    restart: unless-stopped
    image: adguard/adguardhome
    network_mode: host
    volumes:
      - /home/qdeli/self-hosted/adguard/work2:/opt/adguardhome/work
      - /home/qdeli/self-hosted/adguard/conf2:/opt/adguardhome/conf
    ports:
      - 8889:80
      - 53:53/udp
      - 53:53/tcp
      - 3000:3000
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /home/qdeli/self-hosted/homarr/configs:/app/data/configs
      - /home/qdeli/self-hosted/homarr/icons:/app/public/icons
      - /home/qdeli/self-hosted/homarr/data:/data
    ports:
      - '7575:7575'
  readarr:
    image: lscr.io/linuxserver/readarr:arm64v8-nightly
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/qdeli/self-hosted/media/config:/config
      - /home/qdeli/self-hosted/media/books:/books #optional
      - /home/qdeli/self-hosted/downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=9797
      - TORRENTING_PORT=6881
    volumes:
      - /home/qdeli/self-hosted/media/qbittorrent/appdata:/config
      - /home/qdeli/self-hosted/media/downloads:/downloads #optional
    ports:
      - 9797:9797
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/qdeli/self-hosted/media/nzbget/data:/config
      - /home/qdeli/self-hosted/media/downloads:/downloads #optional
    ports:
      - 6789:6789
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/qdeli/self-hosted/nginx/data:/data
      - /home/qdeli/self-hosted/nginx/letsencrypt:/etc/letsencrypt
      - /home/qdeli/self-hosted/nginx/snoppets:/snippets:ro