version: "3"
services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    deploy:
      mode: global